### ISSUE TITLE
Cluster-specific example

### ISSUE THREAD

**Issue by euskode** [indutny/sticky-session#1]
I think, given the nature of the module, that it would make most sense to show a simple example where sticky-session is being used in conjunction with cluster. I realize that the current example gets the point across for people familiar with both socket.io and cluster, but it would really help put things into perspective if the example showed the module in action with the two other technologies that it is meant to interface with.

**Comment by yordadev** [comment]
interest -- please show

**Comment by elewin** [comment]
I too would be very interested in this. Just a bare bones, stripped down example with cluster would be amazing
