### ISSUE TITLE
doesn't work on socket.io 1.2.1 

### ISSUE THREAD

**Issue by ofirzh** [indutny/sticky-session#19]
doesn't work on socket.io 1.2.1. Workers get the random connections.

line52    // Pass connection to worker
line53      worker = workers[ipHash % workers.length];

if you change to static number you will see that this doesn't affect.

Regards,
Ofir.

**Comment by ofirzh** [comment]
doesn't work on socket.io 1.2.0 also

**Comment by indutny** [comment]
@ofirzh may I ask you to create a gist or repo with an example code? Ideally, I should be able to just `npm install` and `node server.js` to test it.

**Comment by ofirzh** [comment]
i don't know how to do it ) i may send you my+yours modified file.
BTW:  doesn't support socket.io 1.1.0 also

**Comment by indutny** [comment]
@ofirzh when you say:

> doesn't support socket.io

What do you mean? How do you check it?

**Comment by ofirzh** [comment]
ok. i have two ways to check.
First in server i have some lines :
    io.on('connection', function(socket){
	  //console.log('socket connected to worker:  ' + process.workerId);
	  socket.on('disconnect', function(socket){
		  console.log('socket disconnected from worker:  ' + process.workerId);
		});
	}); 
i added line to sticky-session.js in worker block (i mean in else of if isMater)
process.workerId = cluster.worker.id; 
for getting workerId in future.

So, when i kill tester i see from there sockets are disconnected.

**Comment by ofirzh** [comment]
And second way. when i do http get on sever (curl localhost:3000) the server returns me which instance (node worker) got the request and does emit to all it's socket  .
My tester counts sockets events and i see how many connections has that worker.
despite i changed to route all connections to workes[0]  the results says that it works only per 1.0.1

**Comment by indutny** [comment]
Ok, so you have some javascript file with a code that starts the server. May I ask you to paste it as a gist?

**Comment by ofirzh** [comment]
Yes. i have. But it contains IPC ( redis pub/sub) i need to remove all stuff that not relevant for this issue. for more clear test case. Let me 10-20 mins i will prepare server.js + modified sticky-session and packge.json. you will need copy and do npm install .
Where i can post this 3 files?
Thanks,
Ofir)

**Comment by indutny** [comment]
https://gist.github.com/ supports multiple files ;) Thank you!

**Comment by ofirzh** [comment]
I prepared gist)
https://gist.github.com/ofirzh/3c46982e9521e3062b51

or under my username)

Thanks a lot)

**Comment by ofirzh** [comment]
Sorry. The issue was from my side. I did server.listen() inside callback and 
not like documented  sticky(callback).listen(...).

You may CLOSE that issue.

tnx for quick response.

**Comment by indutny** [comment]
np!

**Comment by ofirzh** [comment]
BTW do you speak russian ?

**Comment by indutny** [comment]
I do, a bit.

**Comment by ofirzh** [comment]
me too ( a bit) may i ask you some questions in the future by email ?
