### ISSUE TITLE
Searching for new maintainer

### ISSUE THREAD

**Issue by indutny** [indutny/sticky-session#29]
Hello everyone!

It looks like I didn't have time for this project for quite awhile now. If you feel like you could `watch` the repo and triage the incoming issues, work on new features, and do releases - please comment on this issue ;)

Going to give away the maintainer rights on both npm and github.

Cheers!

**Comment by thebigredgeek** [comment]
Hey,

I'd be down.

Andrew

**Comment by indutny** [comment]
Sure, go ahead.

**Comment by indutny** [comment]
I have added you github perms so far. Let me know if you'll need to do npm release ;)

**Comment by indutny** [comment]
Thanks!
