### ISSUE TITLE
Sticky is not a function

### ISSUE THREAD

**Issue by danwguy** [indutny/sticky-session#46]
I have been scouring the web for hours trying to find out the answer to this question and nothing has shown up. I found an example on github using sticky-session v0.1.0. it uses this is in the code...
sticky(worker, function() {
    var server = http.createServer(app);
    var io = require('socket.io')(server);

    addRediAdapter(io);
    addIOEventHandler(io);
    return server;
}).listen(port, function() {
    console.log('server started on port ' + port + '. process id=' + process.pid);
});
it can be found here .... https://github.com/evilstudios/chat-example-cluster
I tried to update to sticky-session v1.x.x but whenever I try to run the server I get the error...
Typeerror: sticky is not a function ...

I have been trying to find out how to upgrade that code to the new stick-session version, but there is absolutely nothing out there on the web for this. Please help me. I am sorry I opened an issue for this, I honestly know no other way to contact anyone and ask this question. Please help. My email is danwguy@gmail.com
Thank you

**Comment by indutny** [comment]
Hello!

I'm afraid the API has changed a bit in v1.x.x, you may find the most recent data here:

https://github.com/indutny/sticky-session#usage

Thank you!
