### ISSUE TITLE
Express example

### ISSUE THREAD

**Issue by ghost** [indutny/sticky-session#7]
I tried the following configuration, but it didn't worked well.

```
var express         = require('express'),
    http            = require('http'),
    socket          = require('socket.io'),
    sticky          = require('sticky-session'),
    APP_PORT        = 8080;

//Create a new instance

var ServerApp           = express(),
    HttpServer          = http.createServer(ServerApp),
    io                  = socket(HttpServer);

sticky(HttpServer).listen(APP_PORT, function()
{
    console.log('Server listening at port %d', APP_PORT);
});
ServerApp.use(express.static(__dirname + '/public/'));
```

The server startup but doesn't serve the static files.

Can you provide an example with the Express framework please?

**Comment by mlabieniec** [comment]
I have the same problem with express :(

**Comment by acutexyz** [comment]
Same. In my case Firefox can't load static files, it just keeps waiting/loading. It's working on Chrome though, but I guess it's using cached versions of files. @indutny @tlhunter?

**Comment by IngwiePhoenix** [comment]
Has this been resolved o.o...? I need to get my Socket.io to be sticky in a clustered environment, and my app is based on Express 4 + Socket.io 1.3.x

**Comment by thebigredgeek** [comment]
I am also having trouble with this.  I think this module worked with express 3.

**Comment by pertinax** [comment]
Hello guys, I'm using express 4.12.3 and socket.io 1.3.5 . Just copy and paste the following boilerplate, should work like a charm - tested on windows 7 and ubuntu 14.04

```
var express = require('express')();
var server = require('http').createServer(express);
var io = require ('socket.io').listen(server);

sticky(server).listen(3000, function() {
  console.log('server started on 3000 port');
});
```

**Comment by afrantz** [comment]
@pertinax :
I just copy / paste your exemple.
Then I test a connexion with supertest in mocha.
I saw the "console.log ('socket')" on my console but my callback is never called in my test :
```javascript
client.on('connection', function() {
    console.log('Test connexion passed');
    return done();
});
```
Node 0.12.7
express 4.13.3
socket.io 1.3.6
sticky-session 0.1.0
socket.io-client 1.3.6

Do you have an idea ?
Thanks.

**Comment by zwhitchcox** [comment]
I'm getting an error, `sticky is not a function`, when I paste your solution, @ivaylopivanov

**Comment by mato75** [comment]
How does this work, I would really appreciate a working example, because on what is written here and what in readme, it looks like two different implementations.

**Comment by binhgo** [comment]
I'm getting an error, sticky is not a function, when I paste your solution, @ivaylopivanov

-> using this bro: 
-> var sticky = require('socketio-sticky-session');

more from this page: https://www.npmjs.com/package/socketio-sticky-session

@zwhitchcox

**Comment by binhgo** [comment]
@mato75 

I will upload the example tonight

**Comment by urieluvd** [comment]
I´m getting 
`c:\ws\src\stream_base.h:217: Assertion '(consumed_) == (false)' failed.`

with both sticky-session and socketio-sticky-session, why?

**Comment by indutny** [comment]
@lorduriel which node.js version are you using?

**Comment by urieluvd** [comment]
@indutny  Node v6.6.0, Windows 10 64-bit

**Comment by igrowheart** [comment]
I'm having similar issue when node is trying to listen on two ports, my App need to listen to both http and https:
```
c:\ws\src\stream_base.h:217: Assertion `(consumed_) == (false)' failed.
```
It works when I comment either section (http or https).

Windows 2012 R2
Node: 6.7.0
sticky-session: 1.12

My code (sorry I can only post the part of related code):




```
...
var sticky = require('sticky-session');
...
// listen on http (start app with node server.js) ======================================
var http_server = http.createServer(app);
sticky.listen(http_server, port, () => {
  logger.info("[server]", "App listening HTTP on port " + port);
});
http_server.on('error', (e) => {
  if (e.code == 'EADDRINUSE') {
    logger.error(e.code + ': Port ' + port + ' already in use, please change it in config.properties');
  }
});
...
// listen on https 
const KEY = 'ssl/server-key.pem';
const CERT = 'ssl/server-cert.pem';
try {
  fs.statSync(KEY);
  fs.statSync(CERT);
  var server_options = {
    key: fs.readFileSync(KEY),
    cert: fs.readFileSync(CERT),
    ca: fs.readFileSync(CERT) 
  };
  var https_server = https.createServer(server_options, app);

  sticky.listen(https_server, https_port, () => {	  
    logger.info("[server]", "App listening HTTPS on port " + https_port);
  });
  
  https_server.on('error', (e) => {
    if (e.code == 'EADDRINUSE') {
      logger.error(e.code + ': Port ' + https_port + ' already in use, please change it in config.properties');
    }
  });
} catch (e) {
  logger.warn("[server]", "HTTPS is not set correctly");
}
...
```

**Comment by urieluvd** [comment]
I solved my issue.
I don´t know where exactly was the problem but changed mi code as follows

before, I had an express api in the same server as socket.io
```
//connectionServer.js
const expressApi = require('./myExpressApi').expressApi;
const http = require('http').Server(expressApi);
const io = require('socket.io')(http);
//other server apis...
```

And in the cluster implementation
```
const io =connectionServer.io;
const serv0=authServer.http;

const ioRedis = require('ioredis');

const pub = new ioRedis(6379 , 'localhost',{ return_buffers: true });
const sub = new ioRedis( 6379 , 'localhost',{ return_buffers: true });

const redis = require('socket.io-redis'); 
 
io.adapter(redis({ host: 'localhost', port: 6379 })); 

if (cluster.isMaster) {
for (var i = 0; i < numCPUs; i++) {
    cluster.fork();
  }
  cluster.on('exit', (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
} 
else {

   sticky(function() {
     return connectionServer.http;
   }).listen(3000, function() {
     console.log('server started on 3000 port');
   });
}

```

And now i have socket.io and the express api in a different  server


```
//connectionServer.js
const expressApi = require('./myExpressApi').expressApi;
const http = require('http').Server();
const http2 = require('http').Server(expressApi);
const io = require('socket.io')(http);
```

And the sticky outside the nonMaster process

```
const io =connectionServer.io;
const serv1=connectionServer.http;//socket
const serv2=connectionServer.http2;//api

const ioRedis = require('ioredis');

const pub = new ioRedis(6379 , 'localhost',{ return_buffers: true });
const sub = new ioRedis( 6379 , 'localhost',{ return_buffers: true });

const redis = require('socket.io-redis'); 
 
io.adapter(redis({ host: 'localhost', port: 6379 })); 

if (cluster.isMaster) {
   
}else{
serv2.listen(3002, function(){
    console.log('Agency Listening on Port 3002');
  });
}

  sticky(
    function () {
      io.listen(serv1);
      return serv1;
    }).listen(3001, function(){
    console.log('Connection Listening on Port 3001');
  });
```


I don´t know what was the problem in the old structure but i just decided to isolate as much as possible each server and api, and it solved it. Now, thinking of it, for my implementation it was wrong to have an api and io on the same server, even if it worked without sticky, now its solved.
@indutny  could have been it my error?
